<a href="https://colab.research.google.com/github/nkatara/iiit-ai-ml/blob/main/U1W2_04_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint
## Not For Grading

### Learning Objective

At the end of this experiment, you will be able to :

* Use Numpy Library

## Setup Steps

In [145]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2501952" #@param {type:"string"}


In [146]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "8439328088" #@param {type:"string"}


In [147]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "U1W2_04_Numpy_Exercise" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/diabetes.csv")
    display(HTML('<script src="https://dashboard.talentsprint.com/submissions/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():

    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword(), "batch" : ""}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts() and getComments():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "id" : Id, "file_hash" : file_hash,
              "feedback_experiments_input" : Comments, "notebook" : notebook, "batch" : ""}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions")
        # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()

else:
  print ("Please complete Id and Password cells before running setup")


Setup completed successfully


## 1. Import the numpy package under the name np

Hint: import … as

In [148]:
# YOUR CODE HERE
import numpy as np

### 2. Print the numpy version and the configuration

Hint: `np.__version__`, `np.show_config()`

In [149]:
# YOUR CODE HERE
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


### 3. Create an array of 10 zeros

Hint:: np.zeros

In [150]:
# YOUR CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Create an array of 10 zeros where the fifth element value is set to 1

Hint: array[4]

In [151]:
# YOUR CODE HERE
zeroArray = np.zeros(10)
zeroArray[4] = 1
zeroArray

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 5. Create an array with values ranging from 10 to 49 (inclusive) and reverse it

Hint: arange

In [152]:
# YOUR CODE HERE
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 6. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

Hint: np.nonzero

In [153]:
# YOUR CODE HERE
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

### 7. Create a 3x3 identity matrix

Hint: np.eye

In [154]:
# YOUR CODE HERE
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8. Create a 3x3x3 array with random values

Hint: np.random.random

In [155]:
# YOUR CODE HERE
np.random.random((3,3,3))

array([[[0.44307278, 0.40019297, 0.34840948],
        [0.01697854, 0.55856995, 0.68339456],
        [0.89717825, 0.75279668, 0.72989851]],

       [[0.50731143, 0.69833258, 0.46237568],
        [0.31710573, 0.31646379, 0.2048233 ],
        [0.99867804, 0.74324372, 0.84318719]],

       [[0.23447128, 0.04436375, 0.6706817 ],
        [0.56433035, 0.68594425, 0.48578121],
        [0.01394265, 0.69935849, 0.41086325]]])

### 9. Create an array of all the even numbers from 30 to 70 (inclusive)

In [156]:
# YOUR CODE HERE
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

### 10. Generate 10x10 array with random integers between 0 to 4 (inclusive) and find the minimum and maximum values

Hint: min, max

In [157]:
# YOUR CODE HERE
arr = np.random.randint(0,5,(10,10))
print(arr)
minValue = arr.min()
print(minValue)
maxValue = arr.max()
print(maxValue)


[[4 1 2 3 1 1 0 0 4 1]
 [3 2 1 2 2 4 1 1 3 4]
 [0 3 0 2 3 0 4 4 3 1]
 [3 1 3 4 1 1 4 0 4 0]
 [2 0 4 2 1 2 2 0 0 0]
 [0 3 4 4 1 2 3 1 4 3]
 [4 4 2 3 4 2 0 3 0 4]
 [3 1 3 3 0 0 2 0 1 4]
 [1 1 1 3 3 2 0 3 2 2]
 [3 1 4 4 4 1 2 1 2 2]]
0
4


### 11. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

Hint: np.diag

In [158]:
# YOUR CODE HERE
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 12. Create an array with values ranging from 20 to 39 (inclusive). Calculate the square root of elements in it.

Hint: np.sqrt( )

In [159]:
# YOUR CODE HERE
np.sqrt(np.arange(20,40))

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

### 13. Transpose the given array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
Hint: np.transpose()

In [160]:
# YOUR CODE HERE
np.transpose([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### 14. Inverse the given array [[3, 4], [5, 6]]
Hint: np.linalg.inv()

In [161]:
# YOUR CODE HERE
m = np.array([[3,4],[5,6]])
np.linalg.inv(m)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

### 15. Concatenate two given arrays by columnwise (specify axis = 1)
Hint:  np.concatenate()

In [162]:
c = np.array([[1, 2],[3, 4]])
d = np.array([[5, 6],[7, 8]])

# YOUR CODE HERE
np.concatenate((c,d),axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 16. Transpose the given arrays and concatenate by columnwise (specify axis = 1)
Hint: np.concatenate()

In [163]:
a = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

# YOUR CODE HERE
np.concatenate((a.transpose(),d.transpose()),axis=1)


array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

### 17. For a given array, print second and third column


In [164]:
a = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])

# YOUR CODE HERE
a[:,1:3]


array([[ 4,  6],
       [ 6,  9],
       [ 8, 12]])

### 18. For a given array, print the values of the second and third rows from the second column.

In [165]:
a = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29],
               [30, 31, 32, 33, 34]])

# YOUR CODE HERE

a[1:3,1:2]



array([[16],
       [21]])

### 19. For a given array perform the following:
#### 1. Calculate mean row wise and column wise by specifying respective axis
#### 2. What is the average value of array

In [166]:
# 2D array
array = np.array([[2, 4, 6, 8, 10],
                  [3, 6, 9, 12, 15],
                  [4, 8, 12, 16, 20]])

# YOUR CODE HERE
print(np.mean(array,axis=1))
print(np.mean(array,axis=0))
print(np.mean(array))


[ 6.  9. 12.]
[ 3.  6.  9. 12. 15.]
9.0


### 20. For a given array, get the slice of the first row from all the 3 matrices and print them.


In [167]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

# YOUR CODE HERE
a3[:, 0, :]

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Please answer the questions below to complete the experiment:




In [168]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good and Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [169]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "Good exercise for learning basic concepts of Numpy" #@param {type:"string"}


In [170]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [171]:
#@title  Experiment walkthrough video? { run: "auto", vertical-output: true, display-mode: "form" }
Walkthrough = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [172]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [173]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [174]:
#@title Run this cell to submit your notebook for Ungrading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 1681
Date of submission:  28 Nov 2025
Time of submission:  08:35:03
View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions
